benchmarks = '../../benchmarks/float/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.dead_store_elimination]
pipeline = [
  "bril2json",
  "python3 ../../examples/task4/alias.py",
  "brili -p {args}",
]