benchmarks = '../examples/test/lvn/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.lvn]
pipeline = [
  "bril2json",
  "python3 ../examples/my_solution/local_vn.py",
  "brili -p {args}",
]