benchmarks = '../examples/test/tdce/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.ldce]
pipeline = [
  "bril2json",
  "python3 ../examples/trivial/local_dce.py",
  "brili -p {args}",
]
