benchmarks = '../benchmarks/mixed/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.const_prop_fold]
pipeline = [
  "bril2json",
  "python3 ../examples/task2/const_prop.py",
  "brili -p {args}",
]