benchmarks = '../../benchmarks/mixed/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.liveness_dce]
pipeline = [
  "bril2json",
  "python3 ../../examples/task2/liveness_dce.py",
  "brili -p {args}",
]

[runs.const_then_live_dce]
pipeline = [
  "bril2json",
  "python3 ../../examples/task2/const_prop.py",
  "python3 ../../examples/task2/liveness_dce.py",
  "brili -p {args}",
]