benchmarks = '../../benchmarks/float/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.const_prop]
pipeline = [
  "bril2json",
  "python3 ../../examples/task2/generic_dataflow_user.py",
  "brili -p {args}",
]