benchmarks = '../../benchmarks/core/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.loop_norm]
pipeline = [
  "bril2json",
  "python3 ../../examples/task3/norm_loops.py",
  "brili -p {args}",
]