benchmarks = '../../benchmarks/mixed/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.convert_ssa]
pipeline = [
  "bril2json",
  "python3 ../../examples/task3/convert_ssa.py",
  "brili -p {args}",
]